
===========
       running command "/usr/bin/dunst -conf /home/sdsaati/.config/qtile/saati/../../dunstrc 2>>/home/sdsaati/.config/qtile/saati/startup_once.log & "      
===========

===========
       running command "/usr/bin/xfsettingsd --daemon -D 2>>/home/sdsaati/.config/qtile/saati/startup_once.log & "      
===========
WARNING: Setting geometry in section global doesn't exist
WARNING: Setting notification_height in section global doesn't exist
WARNING: Setting startup_notification in section global doesn't exist
WARNING: Setting verbosity in section global doesn't exist
CRITICAL: [dbus_cb_name_lost:1152] Cannot acquire 'org.freedesktop.Notifications': Name is acquired by 'dunst' with PID '1511'.

(xfsettingsd:1542): libxfce4kbd-private-WARNING **: 13:03:03.619: Failed to grab keycode 33

(xfsettingsd:1542): libxfce4kbd-private-WARNING **: 13:03:03.621: Failed to grab keycode 107

(xfsettingsd:1542): libxfce4kbd-private-WARNING **: 13:03:03.621: Failed to grab keycode 218
Failed to connect to session manager: Failed to connect to the session manager: SESSION_MANAGER environment variable not defined

===========
       running command "/usr/bin/dbus-launch lxpolkit 2>>/home/sdsaati/.config/qtile/saati/startup_once.log & "      
===========

===========
       running command "/usr/bin/pkexec --keep-cwd /usr/sbin/dnscrypt-proxy "-config /home/sdsaati/.config/qtile/saati/../../dnscrypt.toml" 2>>/home/sdsaati/.config/qtile/saati/startup_once.log"       
===========
(ERROR) Command 'nm-applet' not found.

===========
       running command "/home/sdsaati/bin/oblivion  2>>/home/sdsaati/.config/qtile/saati/startup_once.log & "      
===========

===========
       running command "/usr/bin/nm-tray  2>>/home/sdsaati/.config/qtile/saati/startup_once.log & "      
===========

===========
       running command "/usr/bin/pasystray  2>>/home/sdsaati/.config/qtile/saati/startup_once.log & "      
===========

===========
       running command "/usr/bin/nitrogen --restore 2>>/home/sdsaati/.config/qtile/saati/startup_once.log & "      
===========

===========
       running command "/usr/bin/dropbox start 2>>/home/sdsaati/.config/qtile/saati/startup_once.log & "      
===========

===========
       running command "/usr/sbin/firefox  2>>/home/sdsaati/.config/qtile/saati/startup_once.log & "      
===========

===========
       running command "/usr/bin/blueman-applet  2>>/home/sdsaati/.config/qtile/saati/startup_once.log & "      
===========

(nitrogen:1754): GLib-GObject-CRITICAL **: 13:03:09.278: Attempting to freeze the notification queue for object GtkSettings[0x61255c69d9c0]; Property notification does not work during instance finalization.

(nitrogen:1754): GLib-GObject-CRITICAL **: 13:03:09.278: Attempting to thaw the notification queue for object GtkSettings[0x61255c69d9c0]; Property notification does not work during instance finalization.

(pasystray:1751): Gdk-CRITICAL **: 13:03:09.583: gdk_window_thaw_toplevel_updates: assertion 'window->update_and_descendants_freeze_count > 0' failed
blueman-applet 13.03.09 WARNING  PluginManager:151 __load_plugin: Not loading DhcpClient because its conflict has higher priority
blueman-applet 13.03.09 WARNING  PluginManager:151 __load_plugin: Not loading PPPSupport because its conflict has higher priority
dropbox: load fq extension '/home/sdsaati/.dropbox-dist/dropbox-lnx.x86_64-216.4.4420/cryptography.hazmat.bindings._openssl.abi3.so'
dropbox: load fq extension '/home/sdsaati/.dropbox-dist/dropbox-lnx.x86_64-216.4.4420/cryptography.hazmat.bindings._padding.abi3.so'
dropbox: load fq extension '/home/sdsaati/.dropbox-dist/dropbox-lnx.x86_64-216.4.4420/apex._apex.abi3.so'
dropbox: load fq extension '/home/sdsaati/.dropbox-dist/dropbox-lnx.x86_64-216.4.4420/psutil._psutil_linux.cpython-38-x86_64-linux-gnu.so'
dropbox: load fq extension '/home/sdsaati/.dropbox-dist/dropbox-lnx.x86_64-216.4.4420/psutil._psutil_posix.cpython-38-x86_64-linux-gnu.so'
dropbox: load fq extension '/home/sdsaati/.dropbox-dist/dropbox-lnx.x86_64-216.4.4420/google._upb._message.cpython-38-x86_64-linux-gnu.so'

(xfsettingsd:1542): libxfce4kbd-private-WARNING **: 13:03:10.768: Failed to grab keycode 33

(xfsettingsd:1542): libxfce4kbd-private-WARNING **: 13:03:10.768: Failed to grab keycode 107

(xfsettingsd:1542): libxfce4kbd-private-WARNING **: 13:03:10.771: Failed to grab keycode 218
[2025-01-26 13:03:11] [NOTICE] dnscrypt-proxy 2.0.45
[2025-01-26 13:03:11] [NOTICE] Network connectivity detected
[2025-01-26 13:03:11] [NOTICE] Now listening to 127.0.0.1:53 [UDP]
[2025-01-26 13:03:11] [NOTICE] Now listening to 127.0.0.1:53 [TCP]
[2025-01-26 13:03:11] [NOTICE] Source [public-resolvers] loaded
[2025-01-26 13:03:11] [NOTICE] Firefox workaround initialized
[2025-01-26 13:03:11] [NOTICE] [google] OK (DoH) - rtt: 49ms
[2025-01-26 13:03:12] [NOTICE] [cloudflare] OK (DoH) - rtt: 98ms
[2025-01-26 13:03:12] [NOTICE] Sorted latencies:
[2025-01-26 13:03:12] [NOTICE] -    49ms google
[2025-01-26 13:03:12] [NOTICE] -    98ms cloudflare
[2025-01-26 13:03:12] [NOTICE] Server with the lowest initial latency: google (rtt: 49ms)
[2025-01-26 13:03:12] [NOTICE] dnscrypt-proxy is ready - live servers: 2
dropbox: load fq extension '/home/sdsaati/.dropbox-dist/dropbox-lnx.x86_64-216.4.4420/tornado.speedups.cpython-38-x86_64-linux-gnu.so'
[ERROR glean_core::metrics::ping] Invalid reason code active for ping usage-reporting
dropbox: load fq extension '/home/sdsaati/.dropbox-dist/dropbox-lnx.x86_64-216.4.4420/wrapt._wrappers.cpython-38-x86_64-linux-gnu.so'
dropbox: load fq extension '/home/sdsaati/.dropbox-dist/dropbox-lnx.x86_64-216.4.4420/PyQt5.QtCore.so'
dropbox: load fq extension '/home/sdsaati/.dropbox-dist/dropbox-lnx.x86_64-216.4.4420/PyQt5.sip.so'
dropbox: load fq extension '/home/sdsaati/.dropbox-dist/dropbox-lnx.x86_64-216.4.4420/PyQt5.QtGui.so'
dropbox: load fq extension '/home/sdsaati/.dropbox-dist/dropbox-lnx.x86_64-216.4.4420/PyQt5.QtWidgets.so'
dropbox: load fq extension '/home/sdsaati/.dropbox-dist/dropbox-lnx.x86_64-216.4.4420/PyQt5.QtDBus.so'
WarpPlus error: {"data":{"parameters":{}},"noticeType":"ApplicationParameters","timestamp":"2025-01-26T09:33:42.161Z"}

[ERROR glean_core::metrics::ping] Invalid reason code inactive for ping usage-reporting
[ERROR glean_core::metrics::ping] Invalid reason code inactive for ping usage-reporting
[ERROR glean_core::metrics::ping] Invalid reason code inactive for ping usage-reporting
[ERROR glean_core::metrics::ping] Invalid reason code inactive for ping usage-reporting
[ERROR glean_core::metrics::ping] Invalid reason code inactive for ping usage-reporting
[ERROR glean_core::metrics::ping] Invalid reason code inactive for ping usage-reporting
[1940:0126/144912.436359:ERROR:ssl_client_socket_impl.cc(878)] handshake failed; returned -1, SSL error code 1, net_error -100
[ERROR glean_core::metrics::ping] Invalid reason code active for ping usage-reporting
WarpPlus error: {"data":{"parameters":{}},"noticeType":"ApplicationParameters","timestamp":"2025-01-26T11:31:11.975Z"}

[ERROR glean_core::metrics::ping] Invalid reason code inactive for ping usage-reporting
[ERROR glean_core::metrics::ping] Invalid reason code active for ping usage-reporting

(xfsettingsd:1542): xfconf-WARNING **: 15:46:26.050: Failed to set property "xfwm4::/general/workspace_count": Operation was cancelled
[ERROR glean_core::metrics::ping] Invalid reason code inactive for ping usage-reporting
pasystray-Message: 16:53:37.665: Failed to get source information: No such entity
[2025-01-26 17:03:13] [NOTICE] Sorted latencies:
[2025-01-26 17:03:13] [NOTICE] -    49ms google
[2025-01-26 17:03:13] [NOTICE] -   100ms cloudflare
[2025-01-26 17:03:13] [NOTICE] Server with the lowest initial latency: google (rtt: 49ms)
[ERROR glean_core::metrics::ping] Invalid reason code active for ping usage-reporting
pasystray-Message: 18:53:06.195: Failed to get source information: No such entity
libva info: VA-API version 1.20.0
libva info: Trying to open /usr/lib/x86_64-linux-gnu/dri/iHD_drv_video.so
libva info: Found init function __vaDriverInit_1_20
libva info: va_openDriver() returns 0
[ERROR glean_core::metrics::ping] Invalid reason code inactive for ping usage-reporting
pasystray-Message: 19:06:13.296: Failed to get source information: No such entity
[ERROR glean_core::metrics::ping] Invalid reason code inactive for ping usage-reporting
[ERROR glean_core::metrics::ping] Invalid reason code inactive for ping usage-reporting
[ERROR glean_core::metrics::ping] Invalid reason code inactive for ping usage-reporting
[2025-01-26 21:03:14] [NOTICE] Sorted latencies:
[2025-01-26 21:03:14] [NOTICE] -    51ms google
[2025-01-26 21:03:14] [NOTICE] -   102ms cloudflare
[2025-01-26 21:03:14] [NOTICE] Server with the lowest initial latency: google (rtt: 51ms)
[ERROR glean_core::metrics::ping] Invalid reason code active for ping usage-reporting
[ERROR glean_core::metrics::ping] Invalid reason code active for ping usage-reporting
[ERROR glean_core::metrics::ping] Invalid reason code active for ping usage-reporting
