
===========
       running command "/usr/bin/dunst -conf /home/sdsaati/.config/qtile/saati/../../dunstrc 2>>/home/sdsaati/.config/qtile/saati/startup_once.log & "      
===========

===========
       running command "/usr/bin/xfsettingsd --daemon -D 2>>/home/sdsaati/.config/qtile/saati/startup_once.log & "      
===========
WARNING: Setting geometry in section global doesn't exist
WARNING: Setting notification_height in section global doesn't exist
WARNING: Setting startup_notification in section global doesn't exist
WARNING: Setting verbosity in section global doesn't exist
CRITICAL: [dbus_cb_name_lost:1152] Cannot acquire 'org.freedesktop.Notifications': Name is acquired by 'dunst' with PID '1526'.

(xfsettingsd:1549): libxfce4kbd-private-WARNING **: 05:17:03.566: Failed to grab keycode 33

(xfsettingsd:1549): libxfce4kbd-private-WARNING **: 05:17:03.567: Failed to grab keycode 107

(xfsettingsd:1549): libxfce4kbd-private-WARNING **: 05:17:03.568: Failed to grab keycode 218
Failed to connect to session manager: Failed to connect to the session manager: SESSION_MANAGER environment variable not defined

===========
       running command "/usr/bin/dbus-launch lxpolkit 2>>/home/sdsaati/.config/qtile/saati/startup_once.log & "      
===========

===========
       running command "/usr/bin/pkexec --keep-cwd /usr/sbin/dnscrypt-proxy "-config /home/sdsaati/.config/qtile/saati/../../dnscrypt.toml" 2>>/home/sdsaati/.config/qtile/saati/startup_once.log"       
===========
(ERROR) Command 'nm-applet' not found.

===========
       running command "/home/sdsaati/bin/oblivion  2>>/home/sdsaati/.config/qtile/saati/startup_once.log & "      
===========

===========
       running command "/usr/bin/nm-tray  2>>/home/sdsaati/.config/qtile/saati/startup_once.log & "      
===========

===========
       running command "/usr/bin/nitrogen --restore 2>>/home/sdsaati/.config/qtile/saati/startup_once.log & "      
===========

===========
       running command "/usr/bin/dropbox start 2>>/home/sdsaati/.config/qtile/saati/startup_once.log & "      
===========

===========
       running command "/usr/sbin/firefox  2>>/home/sdsaati/.config/qtile/saati/startup_once.log & "      
===========

===========
       running command "/home/sdsaati/Downloads/Logseq-linux-x64-0.10.9.AppImage --no-sandbox 2>>/home/sdsaati/.config/qtile/saati/startup_once.log & "      
===========

===========
       running command "/usr/bin/blueman-applet  2>>/home/sdsaati/.config/qtile/saati/startup_once.log & "      
===========
blueman-applet 05.17.09 WARNING  PluginManager:151 __load_plugin: Not loading DhcpClient because its conflict has higher priority

(nitrogen:1811): GLib-GObject-CRITICAL **: 05:17:09.890: Attempting to freeze the notification queue for object GtkSettings[0x5818aeb5be40]; Property notification does not work during instance finalization.

(nitrogen:1811): GLib-GObject-CRITICAL **: 05:17:09.890: Attempting to thaw the notification queue for object GtkSettings[0x5818aeb5be40]; Property notification does not work during instance finalization.
blueman-applet 05.17.09 WARNING  PluginManager:151 __load_plugin: Not loading PPPSupport because its conflict has higher priority
dropbox: load fq extension '/home/sdsaati/.dropbox-dist/dropbox-lnx.x86_64-215.4.7202/cryptography.hazmat.bindings._openssl.abi3.so'
dropbox: load fq extension '/home/sdsaati/.dropbox-dist/dropbox-lnx.x86_64-215.4.7202/cryptography.hazmat.bindings._padding.abi3.so'
dropbox: load fq extension '/home/sdsaati/.dropbox-dist/dropbox-lnx.x86_64-215.4.7202/apex._apex.abi3.so'
dropbox: load fq extension '/home/sdsaati/.dropbox-dist/dropbox-lnx.x86_64-215.4.7202/psutil._psutil_linux.cpython-38-x86_64-linux-gnu.so'
dropbox: load fq extension '/home/sdsaati/.dropbox-dist/dropbox-lnx.x86_64-215.4.7202/psutil._psutil_posix.cpython-38-x86_64-linux-gnu.so'
dropbox: load fq extension '/home/sdsaati/.dropbox-dist/dropbox-lnx.x86_64-215.4.7202/google._upb._message.cpython-38-x86_64-linux-gnu.so'

(xfsettingsd:1549): libxfce4kbd-private-WARNING **: 05:17:11.694: Failed to grab keycode 33

(xfsettingsd:1549): libxfce4kbd-private-WARNING **: 05:17:11.695: Failed to grab keycode 107

(xfsettingsd:1549): libxfce4kbd-private-WARNING **: 05:17:11.696: Failed to grab keycode 218
(rsapi) init loggers
dropbox: load fq extension '/home/sdsaati/.dropbox-dist/dropbox-lnx.x86_64-215.4.7202/tornado.speedups.cpython-38-x86_64-linux-gnu.so'
[2025-01-16 05:17:15] [NOTICE] dnscrypt-proxy 2.0.45
[2025-01-16 05:17:15] [NOTICE] Network connectivity detected
[2025-01-16 05:17:15] [NOTICE] Now listening to 127.0.0.1:53 [UDP]
[2025-01-16 05:17:15] [NOTICE] Now listening to 127.0.0.1:53 [TCP]
[2025-01-16 05:17:15] [NOTICE] Source [public-resolvers] loaded
[2025-01-16 05:17:15] [NOTICE] Firefox workaround initialized
[2025-01-16 05:17:15] [NOTICE] [google] OK (DoH) - rtt: 54ms
[ERROR glean_core::metrics::ping] Invalid reason code active for ping usage-reporting
[2025-01-16 05:17:16] [NOTICE] [cloudflare] OK (DoH) - rtt: 104ms
[2025-01-16 05:17:16] [NOTICE] Sorted latencies:
[2025-01-16 05:17:16] [NOTICE] -    54ms google
[2025-01-16 05:17:16] [NOTICE] -   104ms cloudflare
[2025-01-16 05:17:16] [NOTICE] Server with the lowest initial latency: google (rtt: 54ms)
[2025-01-16 05:17:16] [NOTICE] dnscrypt-proxy is ready - live servers: 2
dropbox: load fq extension '/home/sdsaati/.dropbox-dist/dropbox-lnx.x86_64-215.4.7202/wrapt._wrappers.cpython-38-x86_64-linux-gnu.so'
dropbox: load fq extension '/home/sdsaati/.dropbox-dist/dropbox-lnx.x86_64-215.4.7202/PyQt5.QtCore.so'
dropbox: load fq extension '/home/sdsaati/.dropbox-dist/dropbox-lnx.x86_64-215.4.7202/PyQt5.sip.so'
dropbox: load fq extension '/home/sdsaati/.dropbox-dist/dropbox-lnx.x86_64-215.4.7202/PyQt5.QtGui.so'
dropbox: load fq extension '/home/sdsaati/.dropbox-dist/dropbox-lnx.x86_64-215.4.7202/PyQt5.QtWidgets.so'
dropbox: load fq extension '/home/sdsaati/.dropbox-dist/dropbox-lnx.x86_64-215.4.7202/PyQt5.QtDBus.so'
Error occurred in handler for 'main': FetchError: request to https://raw.githubusercontent.com/logseq/marketplace/master/plugins.json failed, reason: connect ECONNREFUSED 127.0.0.1:8086
    at ClientRequest.<anonymous> (/tmp/.mount_LogseqRNhmGT/resources/app/node_modules/node-fetch/lib/index.js:1491:11)
    at ClientRequest.emit (node:events:514:28)
    at _destroy (node:_http_client:882:13)
    at onSocketNT (node:_http_client:902:5)
    at process.processTicksAndRejections (node:internal/process/task_queues:83:21) {
  type: 'system',
  errno: undefined,
  code: undefined
}

(xfsettingsd:1549): xfconf-WARNING **: 05:18:47.540: Failed to set property "xfwm4::/general/workspace_count": Operation was cancelled
Warning: terminator_CreateInstance: Failed to CreateInstance in ICD 1.  Skipping ICD.

(xfsettingsd:1549): xfconf-WARNING **: 05:19:55.088: Failed to set property "xfwm4::/general/workspace_count": Operation was cancelled

(xfsettingsd:1549): xfconf-WARNING **: 05:20:43.255: Failed to set property "xfwm4::/general/workspace_count": Operation was cancelled

(xfsettingsd:1549): xfconf-WARNING **: 05:21:23.973: Failed to set property "xfwm4::/general/workspace_count": Operation was cancelled

(xfsettingsd:1549): xfconf-WARNING **: 05:21:37.215: Failed to set property "xfwm4::/general/workspace_count": Operation was cancelled

(xfsettingsd:1549): xfconf-WARNING **: 05:21:57.251: Failed to set property "xfwm4::/general/workspace_count": Operation was cancelled

(xfsettingsd:1549): xfconf-WARNING **: 05:23:03.663: Failed to set property "xfwm4::/general/workspace_count": Operation was cancelled
WarpPlus error: {"data":{"parameters":{}},"noticeType":"ApplicationParameters","timestamp":"2025-01-16T01:53:41.926Z"}

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/blueman/main/DBusProxies.py", line 52, in call_finish
    proxy.call_finish(resp)
gi.repository.GLib.GError: g-dbus-error-quark: GDBus.Error:org.freedesktop.DBus.Error.InvalidArgs: Unknown action ‘Activate’ (16)
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/blueman/main/DBusProxies.py", line 52, in call_finish
    proxy.call_finish(resp)
gi.repository.GLib.GError: g-dbus-error-quark: GDBus.Error:org.freedesktop.DBus.Error.InvalidArgs: Unknown action ‘Activate’ (16)

(xfsettingsd:1549): xfconf-WARNING **: 05:44:20.160: Failed to set property "xfwm4::/general/workspace_count": Operation was cancelled

(xfsettingsd:1549): xfconf-WARNING **: 05:48:07.714: Failed to set property "xfwm4::/general/workspace_count": Operation was cancelled

(xfsettingsd:1549): xfconf-WARNING **: 05:49:21.408: Failed to set property "xfwm4::/general/workspace_count": Operation was cancelled

(xfsettingsd:1549): xfconf-WARNING **: 05:50:17.113: Failed to set property "xfwm4::/general/workspace_count": Operation was cancelled
